import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { getPrisma } from "@/lib/db";
import { isAdmin } from "@/lib/admin-auth";
import { getPaymentReview, resolvePaymentReview } from "@/lib/payment-review";

async function authorize() { const session = await auth(); if (!session?.user) return { status: 401 as const, session: null }; if (!isAdmin(session)) return { status: 403 as const, session: null }; return { status: 200 as const, session }; }
export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { const access = await authorize(); if (access.status !== 200) return NextResponse.json({ error: access.status === 401 ? "Unauthorized" : "Forbidden" }, { status: access.status }); const prisma = getPrisma(); if (!prisma) return NextResponse.json({ error: "Database chưa được cấu hình." }, { status: 503 }); const item = await getPaymentReview(prisma, (await context.params).id).catch(() => null); return item ? NextResponse.json({ ...item, customerPhone: item.customerPhone, guestEmail: item.guestEmail }) : NextResponse.json({ error: "Not found" }, { status: 404 }); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const access = await authorize(); if (access.status !== 200) return NextResponse.json({ error: access.status === 401 ? "Unauthorized" : "Forbidden" }, { status: access.status }); const prisma = getPrisma(); if (!prisma) return NextResponse.json({ error: "Database chưa được cấu hình." }, { status: 503 }); try { return NextResponse.json(await resolvePaymentReview(prisma, access.session.user.id, (await context.params).id, await request.json().catch(() => null))); } catch (error) { const code = error instanceof Error ? error.message : ""; if (code === "NOT_FOUND") return NextResponse.json({ error: "Không tìm thấy payment review." }, { status: 404 }); if (["INVALID_STATE", "INVALID_RESERVATIONS", "ALREADY_RESOLVED", "INSUFFICIENT_STOCK"].includes(code)) return NextResponse.json({ error: code }, { status: 409 }); if (error instanceof Error && error.name === "ZodError") return NextResponse.json({ error: "Payload xử lý không hợp lệ." }, { status: 400 }); return NextResponse.json({ error: "Không thể xử lý payment review." }, { status: 503 }); } }
