import { NextResponse } from "next/server";
import { z } from "zod";
import { auth } from "@/auth";
import { getPrisma } from "@/lib/db";
const input = z.object({ slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120), name: z.string().trim().min(1).max(160), description: z.string().trim().max(5000).nullable().optional(), status: z.enum(["DRAFT", "PUBLISHED"]), sortOrder: z.number().int().min(0) }).partial().strict();
async function editor() { const session = await auth(); return session?.user?.role === "ADMIN" || session?.user?.role === "EDITOR"; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { if (!await editor()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const prisma = getPrisma(); const item = prisma && await prisma.productCategory.findUnique({ where: { id: (await params).id }, include: { _count: { select: { products: true } } } }); return item ? NextResponse.json(item) : NextResponse.json({ error: "Not found" }, { status: 404 }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { if (!await editor()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Dữ liệu không hợp lệ." }, { status: 400 }); const prisma = getPrisma(); if (!prisma) return NextResponse.json({ error: "Database chưa được cấu hình." }, { status: 503 }); try { return NextResponse.json(await prisma.productCategory.update({ where: { id: (await params).id }, data: parsed.data })); } catch { return NextResponse.json({ error: "Không thể cập nhật loại sản phẩm." }, { status: 404 }); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (session?.user?.role !== "ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const prisma = getPrisma(); if (!prisma) return NextResponse.json({ error: "Database chưa được cấu hình." }, { status: 503 }); try { await prisma.productCategory.delete({ where: { id: (await params).id } }); return new NextResponse(null, { status: 204 }); } catch { return NextResponse.json({ error: "Không thể xóa loại sản phẩm đang được dùng." }, { status: 409 }); } }
