"use client";

import { useState } from "react";

type Address = { id: string; label: string | null; fullName: string; phone: string; line1: string; province: string; district: string | null; postalCode: string | null };
const empty = { label: "", fullName: "", phone: "", line1: "", province: "", district: "", postalCode: "" };

export function AccountAddressBook({ initial }: { initial: Address[] }) {
  const [items, setItems] = useState(initial); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  function change(key: keyof typeof empty, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch(editing ? `/api/account/addresses/${editing}` : "/api/account/addresses", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json().catch(() => null); setSaving(false); if (!response.ok) { setMessage(body?.error ?? "Không thể lưu địa chỉ."); return; } setItems((current) => editing ? current.map((item) => item.id === editing ? body : item) : [...current, body]); setForm(empty); setEditing(null); setMessage("Đã lưu địa chỉ."); }
  async function remove(id: string) { const response = await fetch(`/api/account/addresses/${id}`, { method: "DELETE" }); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)); else setMessage("Không thể xóa địa chỉ này."); }
  return <div className="account-address-book"><div className="account-address-list">{items.map((item) => <article className="account-address-card" key={item.id}><strong>{item.label || "Địa chỉ"}</strong><p>{item.fullName} · {item.phone}<br />{item.line1}, {item.district ? `${item.district}, ` : ""}{item.province}{item.postalCode ? ` · ${item.postalCode}` : ""}</p><button className="text-link" onClick={() => { setEditing(item.id); setForm({ label: item.label ?? "", fullName: item.fullName, phone: item.phone, line1: item.line1, province: item.province, district: item.district ?? "", postalCode: item.postalCode ?? "" }); }}>Sửa</button> <button className="text-link" onClick={() => void remove(item.id)}>Xóa</button></article>)}{items.length === 0 && <p className="muted">Bạn chưa lưu địa chỉ nào.</p>}</div><form className="account-form" onSubmit={submit}><h2>{editing ? "Sửa địa chỉ" : "Thêm địa chỉ"}</h2>{(Object.keys(empty) as Array<keyof typeof empty>).map((key) => <label key={key}>{({ label: "Nhãn", fullName: "Họ và tên", phone: "Số điện thoại", line1: "Địa chỉ", province: "Tỉnh / thành phố", district: "Quận / huyện", postalCode: "Mã bưu chính" } as Record<string, string>)[key]}<input required={key === "fullName" || key === "phone" || key === "line1" || key === "province"} autoComplete={key === "fullName" ? "name" : key === "phone" ? "tel" : "street-address"} value={form[key]} onChange={(event) => change(key, event.target.value)} /></label>)}{message && <p role="status" aria-live="polite">{message}</p>}<div><button className="button button-primary" disabled={saving}>{saving ? "Đang lưu…" : "Lưu địa chỉ"}</button>{editing && <button type="button" className="button button-secondary" onClick={() => { setEditing(null); setForm(empty); }}>Hủy</button>}</div></form></div>;
}
