import Link from "next/link";

type DashboardData = Awaited<ReturnType<typeof import("@/lib/admin-dashboard").getAdminDashboard>>;

const labels: Record<string, string> = { PENDING: "Chờ xử lý", CONFIRMED: "Đã xác nhận", PROCESSING: "Đang xử lý", SHIPPED: "Đã giao", COMPLETED: "Hoàn tất", CANCELLED: "Đã hủy" };
const money = (value: number) => `${value.toLocaleString("vi-VN")} ₫`;

function LineChart({ data }: { data: DashboardData["daily"] }) {
  const maximum = Math.max(1, ...data.map((item) => Math.max(item.revenue, item.orders)));
  const points = data.map((item, index) => `${data.length === 1 ? 0 : (index / (data.length - 1)) * 100},${88 - (item.revenue / maximum) * 72}`).join(" ");
  return <div className="ops-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Doanh thu theo ngày"><path d="M0 88 H100" className="ops-chart-base" /><polyline points={points} className="ops-chart-line" /></svg><div className="ops-chart-labels"><span>{data[0]?.date.slice(5)}</span><span>{data.at(-1)?.date.slice(5)}</span></div></div>;
}

export function AdminDashboard({ data, range }: { data: DashboardData; range: "7d" | "30d" }) {
  const alerts = [{ label: "Thanh toán cần kiểm tra", value: data.payments.reviewRequired, href: "/admin/payment-reviews", tone: "danger" }, { label: "Variant hết hàng", value: data.inventory.zeroStockActiveVariants, href: "/admin/inventory", tone: "warning" }, { label: "Variant tồn kho thấp", value: data.inventory.lowStockActiveVariants, href: "/admin/inventory", tone: "warning" }, { label: "Sản phẩm chưa xác minh", value: data.dataQuality.unverifiedProducts, href: "/admin/data-quality", tone: "warning" }, { label: "Lead cần xử lý", value: data.leads.NEW + data.leads.IN_PROGRESS, href: "/admin/leads", tone: "normal" }].filter((item) => item.value > 0);
  return <div className="ops-stack">
    <section className="ops-page-heading"><div><p className="ops-overline">VẬN HÀNH</p><h2>Tình hình kinh doanh</h2><p>Dữ liệu trong {range === "30d" ? "30 ngày" : "7 ngày"} gần đây.</p></div><nav className="ops-segmented"><Link className={range === "7d" ? "active" : ""} href="/admin/dashboard?range=7d">7 ngày</Link><Link className={range === "30d" ? "active" : ""} href="/admin/dashboard?range=30d">30 ngày</Link></nav></section>
    <section className="ops-kpis"><article><span>Đơn hàng</span><strong>{data.orders.total}</strong><small>Trong kỳ đã chọn</small></article><article><span>Doanh thu đã thanh toán</span><strong>{money(data.payments.paidRevenue)}</strong><small>Đơn đã thanh toán</small></article><article><span>Thanh toán chờ</span><strong>{data.payments.pending}</strong><small>Chưa hoàn tất</small></article><article><span>Yêu cầu sau mua</span><strong>{data.afterSales.SUBMITTED + data.afterSales.REVIEWING}</strong><small>Đang cần theo dõi</small></article></section>
    <section className="ops-dashboard-grid"><article className="ops-card ops-chart-card"><div className="ops-card-heading"><div><h3>Doanh thu theo ngày</h3><p>Chỉ tính đơn đã thanh toán</p></div><strong>{money(data.payments.paidRevenue)}</strong></div><LineChart data={data.daily} /></article><article className="ops-card"><div className="ops-card-heading"><div><h3>Trạng thái đơn hàng</h3><p>Phân bổ trong kỳ</p></div></div><div className="ops-status-bars">{Object.entries(data.orders.byStatus).map(([status, count]) => <div key={status}><span>{labels[status] ?? status}</span><i><b style={{ width: `${data.orders.total ? (count / data.orders.total) * 100 : 0}%` }} /></i><strong>{count}</strong></div>)}</div></article></section>
    <section className="ops-card"><div className="ops-card-heading"><div><h3>Cần ưu tiên</h3><p>Các đầu việc ảnh hưởng đến vận hành hoặc điều kiện xuất bản.</p></div><Link href={"/admin/data-quality" as never}>Mở Data Quality →</Link></div><div className="ops-alerts">{alerts.length ? alerts.map((item) => <Link href={item.href as never} key={item.label} className={`ops-alert ${item.tone}`}><span>{item.label}</span><strong>{item.value}</strong><small>Xem →</small></Link>) : <p className="ops-empty">Không có cảnh báo cần xử lý.</p>}</div></section>
    <section className="ops-activity-grid"><Activity title="Đơn hàng gần đây" href="/admin/orders" rows={data.activity.orders.map((item) => [item.code, `${labels[item.status] ?? item.status} · ${money(item.total)}`])} /><Activity title="Khách quan tâm" href="/admin/leads" rows={data.activity.leads.map((item) => [item.fullName, `${item.status} · ${item.phone}`])} /><Activity title="Yêu cầu sau mua" href="/admin/after-sales" rows={data.activity.afterSales.map((item) => [item.subject, `${item.status} · ${item.order.code}`])} /></section>
  </div>;
}

function Activity({ title, href, rows }: { title: string; href: string; rows: string[][] }) { return <section className="ops-card"><div className="ops-card-heading"><h3>{title}</h3><Link href={href as never}>Xem tất cả →</Link></div><div className="ops-activity-list">{rows.length ? rows.map(([title, meta], index) => <Link href={href as never} key={`${title}-${index}`}><strong>{title}</strong><span>{meta}</span></Link>) : <p className="ops-empty">Chưa có dữ liệu.</p>}</div></section>; }
