"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function AdminOrderActions({ orderId, status, paymentMethod, paymentStatus }: { orderId: string; status: string; paymentMethod: string; paymentStatus: string }) {
  const router = useRouter(); const [pending, setPending] = useState(""); const [error, setError] = useState("");
  async function update(action: string, nextStatus?: string) { setPending(action); setError(""); const response = await fetch(`/api/admin/orders/${orderId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(nextStatus ? { status: nextStatus } : { action }) }); const body = await response.json().catch(() => null) as { error?: string } | null; setPending(""); if (!response.ok) { setError(body?.error ?? "Không thể cập nhật đơn hàng."); return; } router.refresh(); }
  return <div className="admin-order-actions">{paymentMethod === "BANK_TRANSFER" && paymentStatus === "PENDING" && <button className="button button-secondary" disabled={Boolean(pending)} onClick={() => void update("confirm_paid")}>{pending === "confirm_paid" ? "Đang xác nhận…" : "Xác nhận đã nhận chuyển khoản"}</button>}{status === "CONFIRMED" && <button className="button button-secondary" disabled={Boolean(pending)} onClick={() => void update("status", "PROCESSING")}>Bắt đầu xử lý</button>}{status === "PROCESSING" && <button className="button button-secondary" disabled={Boolean(pending)} onClick={() => void update("status", "SHIPPED")}>Bàn giao vận chuyển</button>}{paymentMethod === "COD" && status === "SHIPPED" && paymentStatus === "PENDING" && <button className="button button-secondary" disabled={Boolean(pending)} onClick={() => void update("confirm_cod_paid")}>{pending === "confirm_cod_paid" ? "Đang xác nhận…" : "Xác nhận đã thu COD"}</button>}{status === "SHIPPED" && paymentStatus === "PAID" && <button className="button button-secondary" disabled={Boolean(pending)} onClick={() => void update("status", "COMPLETED")}>Hoàn tất đơn hàng</button>}{status !== "CANCELLED" && status !== "SHIPPED" && status !== "COMPLETED" && paymentStatus !== "PAID" && paymentStatus !== "REVIEW_REQUIRED" && <button className="button button-dark" disabled={Boolean(pending)} onClick={() => void update("cancel")}>{pending === "cancel" ? "Đang hủy…" : "Hủy đơn"}</button>}{error && <p className="form-error" role="alert">{error}</p>}</div>;
}
