"use client";
/* eslint-disable @next/next/no-img-element */

import { useState } from "react";

const tabs = ["General", "Content", "Pricing", "Variants", "Media", "Construction", "Inventory", "Shipping", "SEO"] as const;
type Tab = typeof tabs[number];
type PublishedTextDraft = { published: boolean; title: string; body: string };
type PublishedBodyDraft = { published: boolean; title: string; body: string };
type ComfortDraft = { published: boolean; firmnessLabel: string; firmnessScore: number | null; support: number | null; breathability: number | null; motionIsolation: number | null };
export type AdminContentDraft = { comfort: ComfortDraft; audience: PublishedTextDraft; materialStory: PublishedTextDraft; delivery: PublishedBodyDraft; warranty: PublishedBodyDraft };
export type AdminDocument = {
  updatedAt: string;
  general: { name: string; eyebrow: string | null; description: string | null; status: "PUBLISHED" | "DRAFT"; isDemo: boolean; mattressLab: boolean; modelUrl: string | null; posterUrl: string | null; content: AdminContentDraft | null };
  variants: Array<{ id?: string; width: number; length: number; thickness: number; price: number | null; compareAtPrice: number | null; sku: string; stock: number; active: boolean }>;
  media: Array<{ id?: string; type: "image" | "video" | "model"; url: string; alt: string; aspect: string | null; focalX: number; focalY: number; fit: "cover" | "contain"; sortOrder: number; isDemo: boolean }>;
  layers: Array<{ id?: string; sortOrder: number; name: string; material: string | null; thickness: string | null; description: string | null; textureUrl: string | null; nodeName: string | null; explodeDistance: number; showHotspot: boolean; published: boolean }>;
};

function emptyContent(): AdminContentDraft { return { comfort: { published: false, firmnessLabel: "", firmnessScore: null, support: null, breathability: null, motionIsolation: null }, audience: { published: false, title: "", body: "" }, materialStory: { published: false, title: "", body: "" }, delivery: { published: false, title: "", body: "" }, warranty: { published: false, title: "", body: "" } }; }
function normalizeScore(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value : null; }
export function normalizeContent(value: unknown): AdminContentDraft {
  const source = (value && typeof value === "object" ? value : {}) as Record<string, unknown>;
  const text = (key: string, optionalTitle = false) => { const item = source[key] as Record<string, unknown> | undefined; return { published: item?.published === true, title: typeof item?.title === "string" ? item.title : "", body: typeof item?.body === "string" ? item.body : "" }; };
  const rawComfort = source.comfort as Record<string, unknown> | undefined;
  return { comfort: { published: rawComfort?.published === true, firmnessLabel: typeof rawComfort?.firmnessLabel === "string" ? rawComfort.firmnessLabel : "", firmnessScore: normalizeScore(rawComfort?.firmnessScore), support: normalizeScore(rawComfort?.support), breathability: normalizeScore(rawComfort?.breathability), motionIsolation: normalizeScore(rawComfort?.motionIsolation) }, audience: text("audience"), materialStory: text("materialStory"), delivery: text("delivery", true), warranty: text("warranty", true) };
}
function hasTitledText(item: { title: string; body: string }) { return Boolean(item.title.trim() && item.body.trim()); }
function hasBody(item: { body: string }) { return Boolean(item.body.trim()); }
export function serializeContent(content: AdminContentDraft | null) {
  if (!content) return undefined;
  const output: Record<string, unknown> = {};
  const comfort = content.comfort;
  if (comfort.firmnessLabel.trim() || [comfort.firmnessScore, comfort.support, comfort.breathability, comfort.motionIsolation].some((value) => value !== null)) output.comfort = comfort;
  if (hasTitledText(content.audience)) output.audience = { published: content.audience.published, title: content.audience.title, body: content.audience.body };
  if (hasTitledText(content.materialStory)) output.materialStory = { published: content.materialStory.published, title: content.materialStory.title, body: content.materialStory.body };
  if (hasBody(content.delivery)) output.delivery = { published: content.delivery.published, ...(content.delivery.title.trim() ? { title: content.delivery.title } : {}), body: content.delivery.body };
  if (hasBody(content.warranty)) output.warranty = { published: content.warranty.published, ...(content.warranty.title.trim() ? { title: content.warranty.title } : {}), body: content.warranty.body };
  return Object.keys(output).length ? output : undefined;
}

function normalizeProduct(value: Record<string, unknown>): AdminDocument {
  const general = value.general as Record<string, unknown> | undefined;
  return { updatedAt: String(value.updatedAt ?? new Date().toISOString()), general: { name: String(general?.name ?? value.name ?? ""), eyebrow: (general?.eyebrow ?? value.eyebrow ?? null) as string | null, description: (general?.description ?? value.description ?? null) as string | null, status: (general?.status ?? value.status ?? "DRAFT") as "PUBLISHED" | "DRAFT", isDemo: Boolean(general?.isDemo ?? value.isDemo), mattressLab: Boolean(general?.mattressLab ?? value.mattressLab), modelUrl: (general?.modelUrl ?? value.modelUrl ?? null) as string | null, posterUrl: (general?.posterUrl ?? value.posterUrl ?? null) as string | null, content: normalizeContent(general?.content ?? value.content) }, variants: ((value.variants ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), width: Number(item.width), length: Number(item.length), thickness: Number(item.thickness), price: item.price === null ? null : Number(item.price), compareAtPrice: item.compareAtPrice == null ? null : Number(item.compareAtPrice), sku: String(item.sku), stock: Number(item.stock), active: Boolean(item.active) })), media: ((value.media ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), type: item.type as "image" | "video" | "model", url: String(item.url), alt: String(item.alt), aspect: (item.aspect ?? null) as string | null, focalX: Number(item.focalX ?? .5), focalY: Number(item.focalY ?? .5), fit: (item.fit ?? "cover") as "cover" | "contain", sortOrder: Number(item.sortOrder), isDemo: Boolean(item.isDemo) })), layers: ((value.layers ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), sortOrder: Number(item.sortOrder), name: String(item.name), material: (item.material ?? null) as string | null, thickness: (item.thickness ?? null) as string | null, description: (item.description ?? null) as string | null, textureUrl: (item.textureUrl ?? null) as string | null, nodeName: (item.nodeName ?? null) as string | null, explodeDistance: Number(item.explodeDistance ?? 0), showHotspot: Boolean(item.showHotspot), published: Boolean(item.published) })) };
}

export function AdminProductEditor({ initialDocument, productId, slug = "luxury" }: { initialDocument: AdminDocument; productId: string; slug?: string }) {
  const [tab, setTab] = useState<Tab>("General"); const [document, setDocument] = useState<AdminDocument>(() => ({ ...initialDocument, general: { ...initialDocument.general, content: initialDocument.general.content ? normalizeContent(initialDocument.general.content) : emptyContent() } })); const [saved, setSaved] = useState<"saved" | "draft" | "saving" | "error">("draft"); const [error, setError] = useState("");
  function updateGeneral<K extends keyof AdminDocument["general"]>(key: K, value: AdminDocument["general"][K]) { setDocument((current) => ({ ...current, general: { ...current.general, [key]: value } })); setSaved("draft"); }
  function updateContent<K extends keyof AdminContentDraft>(key: K, value: AdminContentDraft[K]) { setDocument((current) => ({ ...current, general: { ...current.general, content: { ...(current.general.content ?? emptyContent()), [key]: value } } })); setSaved("draft"); }
  function updateVariant(index: number, patch: Partial<AdminDocument["variants"][number]>) { setDocument((current) => ({ ...current, variants: current.variants.map((variant, itemIndex) => itemIndex === index ? { ...variant, ...patch } : variant) })); setSaved("draft"); }
  function updateMedia(index: number, patch: Partial<AdminDocument["media"][number]>) { setDocument((current) => ({ ...current, media: current.media.map((media, itemIndex) => itemIndex === index ? { ...media, ...patch } : media) })); setSaved("draft"); }
  function updateLayer(index: number, patch: Partial<AdminDocument["layers"][number]>) { setDocument((current) => ({ ...current, layers: current.layers.map((layer, itemIndex) => itemIndex === index ? { ...layer, ...patch } : layer) })); setSaved("draft"); }
  async function save() { setSaved("saving"); setError(""); const payload = { ...document, general: { ...document.general, content: serializeContent(document.general.content) ?? null }, variants: document.variants.map(({ stock: _stock, ...variant }) => variant) }; const response = await fetch(`/api/admin/products/${slug}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null) as Record<string, unknown> | null; if (!response.ok || !body) { setSaved("error"); setError(response.status === 409 ? "Sản phẩm đã được sửa ở nơi khác. Hãy tải lại trước khi lưu." : String(body?.error ?? "Không thể lưu sản phẩm.")); return; } setDocument(normalizeProduct(body)); setSaved("saved"); }
  async function upload(file: File) { setError(""); const kind = file.type.startsWith("image/") ? "image" : file.type === "video/mp4" ? "video" : file.type === "model/gltf-binary" ? "model" : null; if (!kind) { setError("Định dạng upload không được hỗ trợ."); return; } const presign = await fetch("/api/uploads/presign", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, contentType: file.type, fileName: file.name, size: file.size }) }); const intent = await presign.json() as { url?: string; intentId?: string; error?: string }; if (!presign.ok || !intent.url || !intent.intentId) { setError(intent.error ?? "Không thể tạo upload intent."); return; } const put = await fetch(intent.url, { method: "PUT", headers: { "content-type": file.type }, body: file }); if (!put.ok) { setError("Upload lên kho lưu trữ thất bại."); return; } const finalized = await fetch("/api/uploads/finalize", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ intentId: intent.intentId, productId, alt: file.name }) }); if (!finalized.ok) { setError("Không thể xác nhận media."); return; } window.location.reload(); }
  const content = document.general.content ?? emptyContent();
  const textEditor = (key: "audience" | "materialStory" | "delivery" | "warranty", title: string, optionalTitle = false) => { const value = content[key]; return <fieldset className="admin-content-block"><legend>{title}</legend><label>Published<input type="checkbox" checked={value.published} onChange={(event) => updateContent(key, { ...value, published: event.target.checked })} /></label>{!optionalTitle && <label>Title<input value={value.title} onChange={(event) => updateContent(key, { ...value, title: event.target.value })} /></label>}{optionalTitle && <label>Title (optional)<input value={value.title} onChange={(event) => updateContent(key, { ...value, title: event.target.value })} /></label>}<label>Body<textarea rows={4} value={value.body} onChange={(event) => updateContent(key, { ...value, body: event.target.value })} /></label></fieldset>; };
  return <div className="admin-editor"><div className="admin-tabs" role="tablist">{tabs.map((item) => <button key={item} className={item === tab ? "active" : ""} onClick={() => setTab(item)} role="tab" aria-selected={item === tab}>{item}</button>)}</div><div className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">{tab.toUpperCase()}</p><h2>{tab === "Construction" ? "Mattress Lab" : `Product ${tab}`}</h2></div><span className="admin-saved">{saved === "saved" ? "Saved just now" : saved === "saving" ? "Saving…" : saved === "error" ? "Save failed" : "Draft changes"}</span></div>
    {tab === "General" && <div className="admin-form"><label>Product name<input value={document.general.name} onChange={(event) => updateGeneral("name", event.target.value)} /></label><label>Eyebrow<input value={document.general.eyebrow ?? ""} onChange={(event) => updateGeneral("eyebrow", event.target.value || null)} /></label><label className="full">Description<textarea value={document.general.description ?? ""} onChange={(event) => updateGeneral("description", event.target.value || null)} rows={5} /></label><label>Status<select value={document.general.status} onChange={(event) => updateGeneral("status", event.target.value as "DRAFT" | "PUBLISHED")}><option value="PUBLISHED">PUBLISHED</option><option value="DRAFT">DRAFT</option></select></label><label>Demo product<input type="checkbox" checked={document.general.isDemo} onChange={(event) => updateGeneral("isDemo", event.target.checked)} /></label><label>Mattress Lab<input type="checkbox" checked={document.general.mattressLab} onChange={(event) => updateGeneral("mattressLab", event.target.checked)} /></label><label className="full">Poster URL<input value={document.general.posterUrl ?? ""} onChange={(event) => updateGeneral("posterUrl", event.target.value || null)} /></label><label className="full">Model URL<input value={document.general.modelUrl ?? ""} onChange={(event) => updateGeneral("modelUrl", event.target.value || null)} /></label></div>}
    {tab === "Content" && <div className="admin-content-grid"><fieldset className="admin-content-block"><legend>Comfort</legend><label>Published<input type="checkbox" checked={content.comfort.published} onChange={(event) => updateContent("comfort", { ...content.comfort, published: event.target.checked })} /></label><label>Firmness label<input value={content.comfort.firmnessLabel} onChange={(event) => updateContent("comfort", { ...content.comfort, firmnessLabel: event.target.value })} /></label>{(["firmnessScore", "support", "breathability", "motionIsolation"] as const).map((field) => <label key={field}>{field}<input type="number" min="1" max="5" step="1" value={content.comfort[field] ?? ""} onChange={(event) => updateContent("comfort", { ...content.comfort, [field]: event.target.value ? Number(event.target.value) : null })} /></label>)}</fieldset>{textEditor("audience", "Audience")}{textEditor("materialStory", "Material story")}{textEditor("delivery", "Delivery", true)}{textEditor("warranty", "Warranty", true)}</div>}
    {tab === "Pricing" && <div className="admin-note">Giá được lưu trên từng variant. Khi price trống hoặc sản phẩm là demo, storefront hiển thị Liên hệ và khóa checkout.</div>}
    {tab === "Variants" && <div className="admin-table"><div className="admin-row admin-row-head"><span>Variant</span><span>Price</span><span>Stock (read-only)</span><span>Active</span></div>{document.variants.map((variant, index) => <div className="admin-row" key={variant.id ?? `new-${index}`}><span><input aria-label="Width" type="number" value={variant.width} onChange={(event) => updateVariant(index, { width: Number(event.target.value) })} /> × <input aria-label="Length" type="number" value={variant.length} onChange={(event) => updateVariant(index, { length: Number(event.target.value) })} /> × <input aria-label="Thickness" type="number" value={variant.thickness} onChange={(event) => updateVariant(index, { thickness: Number(event.target.value) })} /> <input aria-label="SKU" placeholder="SKU bắt buộc" value={variant.sku} onChange={(event) => updateVariant(index, { sku: event.target.value })} /></span><input aria-label="Price" type="number" min="0" value={variant.price ?? ""} onChange={(event) => updateVariant(index, { price: event.target.value ? Number(event.target.value) : null })} /><output aria-label="Stock">{variant.stock}</output><input aria-label="Active" type="checkbox" checked={variant.active} onChange={(event) => updateVariant(index, { active: event.target.checked })} /></div>)}<button className="button button-secondary" onClick={() => setDocument((current) => ({ ...current, variants: [...current.variants, { width: 160, length: 200, thickness: 15, price: null, compareAtPrice: null, sku: "", stock: 0, active: false }] }))}>Add variant</button></div>}
    {tab === "Media" && <div className="admin-media-grid"><label className="upload-card">+<span>Upload image / video / GLB</span><small>Upload mới luôn là demo; bỏ chọn sau khi xác minh.</small><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,model/gltf-binary,.glb" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label>{document.media.map((file, index) => <div className="media-card" key={file.id ?? file.url}><img src={file.url} alt={file.alt} /><label>Alt<input value={file.alt} onChange={(event) => updateMedia(index, { alt: event.target.value })} /></label><label>Sort order<input type="number" min="0" value={file.sortOrder} onChange={(event) => updateMedia(index, { sortOrder: Number(event.target.value) })} /></label><label>Focal X<input type="number" min="0" max="1" step="0.01" value={file.focalX} onChange={(event) => updateMedia(index, { focalX: Number(event.target.value) })} /></label><label>Focal Y<input type="number" min="0" max="1" step="0.01" value={file.focalY} onChange={(event) => updateMedia(index, { focalY: Number(event.target.value) })} /></label><label>Fit<select value={file.fit} onChange={(event) => updateMedia(index, { fit: event.target.value as "cover" | "contain" })}><option value="cover">cover</option><option value="contain">contain</option></select></label><label className={file.isDemo ? "media-demo-flag" : ""}>Ảnh minh họa/demo<input type="checkbox" checked={file.isDemo} onChange={(event) => updateMedia(index, { isDemo: event.target.checked })} /></label><small>{file.isDemo ? "Đang được xem là minh họa/demo" : "Asset đã xác nhận"}</small><button type="button" className="button button-secondary" onClick={() => setDocument((current) => ({ ...current, media: current.media.filter((_, itemIndex) => itemIndex !== index) }))}>Detach metadata</button></div>)}</div>}
    {tab === "Construction" && <div className="construction-editor"><div className="lab-switch"><span>Mattress Lab</span><input type="checkbox" checked={document.general.mattressLab} onChange={(event) => updateGeneral("mattressLab", event.target.checked)} /></div><label className="upload-card wide">Upload GLB model <small>Lazy loaded on storefront · max 50MB</small><input type="file" accept="model/gltf-binary,.glb" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label>{document.layers.map((layer, index) => <div className="layer-row" key={layer.id ?? `layer-${index}`}><b>{String(layer.sortOrder + 1).padStart(2, "0")}</b><input value={layer.name} onChange={(event) => updateLayer(index, { name: event.target.value })} /><input placeholder="Material" value={layer.material ?? ""} onChange={(event) => updateLayer(index, { material: event.target.value || null })} /><input placeholder="GLB node" value={layer.nodeName ?? ""} onChange={(event) => updateLayer(index, { nodeName: event.target.value || null })} /><input type="checkbox" checked={layer.published} onChange={(event) => updateLayer(index, { published: event.target.checked })} /></div>)}</div>}
    {tab === "Inventory" && <div className="admin-note">Tồn kho được quản lý tại màn Inventory bằng delta. Product editor không ghi stock.</div>}{tab === "Shipping" && <div className="admin-note">Phí vận chuyển và thông tin chuyển khoản được quản lý tại Site settings.</div>}{tab === "SEO" && <div className="admin-note">SEO metadata chỉ được xuất bản khi nội dung đã được xác nhận trong CMS.</div>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary admin-save" disabled={saved === "saving"} onClick={() => void save()}>{saved === "saving" ? "Saving…" : "Save changes"}</button></div></div>;
}
