"use client";
/* eslint-disable @next/next/no-img-element */

import { useState } from "react";

const tabs = ["General", "Pricing", "Variants", "Media", "Construction", "Inventory", "Shipping", "SEO"] as const;
type Tab = typeof tabs[number];

export type AdminDocument = {
  updatedAt: string;
  general: { name: string; eyebrow: string | null; description: string | null; status: "PUBLISHED" | "DRAFT"; isDemo: boolean; mattressLab: boolean; modelUrl: string | null; posterUrl: string | null; content: Record<string, unknown> | null };
  variants: Array<{ id?: string; width: number; length: number; thickness: number; price: number | null; compareAtPrice: number | null; sku: string; stock: number; active: boolean }>;
  media: Array<{ id?: string; type: "image" | "video" | "model"; url: string; alt: string; aspect: string | null; focalX: number; focalY: number; fit: "cover" | "contain"; sortOrder: number; isDemo: boolean }>;
  layers: Array<{ id?: string; sortOrder: number; name: string; material: string | null; thickness: string | null; description: string | null; textureUrl: string | null; nodeName: string | null; explodeDistance: number; showHotspot: boolean; published: boolean }>;
};

function normalizeProduct(value: Record<string, unknown>): AdminDocument {
  const general = value.general as Record<string, unknown> | undefined;
  return {
    updatedAt: String(value.updatedAt ?? new Date().toISOString()),
    general: { name: String(general?.name ?? value.name ?? ""), eyebrow: (general?.eyebrow ?? value.eyebrow ?? null) as string | null, description: (general?.description ?? value.description ?? null) as string | null, status: (general?.status ?? value.status ?? "DRAFT") as "PUBLISHED" | "DRAFT", isDemo: Boolean(general?.isDemo ?? value.isDemo), mattressLab: Boolean(general?.mattressLab ?? value.mattressLab), modelUrl: (general?.modelUrl ?? value.modelUrl ?? null) as string | null, posterUrl: (general?.posterUrl ?? value.posterUrl ?? null) as string | null, content: (general?.content ?? value.content ?? null) as Record<string, unknown> | null },
    variants: ((value.variants ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), width: Number(item.width), length: Number(item.length), thickness: Number(item.thickness), price: item.price === null ? null : Number(item.price), compareAtPrice: item.compareAtPrice == null ? null : Number(item.compareAtPrice), sku: String(item.sku), stock: Number(item.stock), active: Boolean(item.active) })),
    media: ((value.media ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), type: item.type as "image" | "video" | "model", url: String(item.url), alt: String(item.alt), aspect: (item.aspect ?? null) as string | null, focalX: Number(item.focalX ?? .5), focalY: Number(item.focalY ?? .5), fit: (item.fit ?? "cover") as "cover" | "contain", sortOrder: Number(item.sortOrder), isDemo: Boolean(item.isDemo) })),
    layers: ((value.layers ?? []) as Array<Record<string, unknown>>).map((item) => ({ id: String(item.id), sortOrder: Number(item.sortOrder), name: String(item.name), material: (item.material ?? null) as string | null, thickness: (item.thickness ?? null) as string | null, description: (item.description ?? null) as string | null, textureUrl: (item.textureUrl ?? null) as string | null, nodeName: (item.nodeName ?? null) as string | null, explodeDistance: Number(item.explodeDistance ?? 0), showHotspot: Boolean(item.showHotspot), published: Boolean(item.published) })),
  };
}

export function AdminProductEditor({ initialDocument, productId, slug = "luxury" }: { initialDocument: AdminDocument; productId: string; slug?: string }) {
  const [tab, setTab] = useState<Tab>("General");
  const [document, setDocument] = useState(initialDocument);
  const [saved, setSaved] = useState<"saved" | "draft" | "saving" | "error">("draft");
  const [error, setError] = useState("");
  function updateGeneral<K extends keyof AdminDocument["general"]>(key: K, value: AdminDocument["general"][K]) { setDocument((current) => ({ ...current, general: { ...current.general, [key]: value } })); setSaved("draft"); }
  function updateVariant(index: number, patch: Partial<AdminDocument["variants"][number]>) { setDocument((current) => ({ ...current, variants: current.variants.map((variant, itemIndex) => itemIndex === index ? { ...variant, ...patch } : variant) })); setSaved("draft"); }
  function updateLayer(index: number, patch: Partial<AdminDocument["layers"][number]>) { setDocument((current) => ({ ...current, layers: current.layers.map((layer, itemIndex) => itemIndex === index ? { ...layer, ...patch } : layer) })); setSaved("draft"); }
  async function save() {
    setSaved("saving"); setError("");
    const payload = { ...document, variants: document.variants.map(({ stock: _stock, ...variant }) => variant) };
    const response = await fetch(`/api/admin/products/${slug}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const body = await response.json().catch(() => null) as Record<string, unknown> | null;
    if (!response.ok || !body) { setSaved("error"); setError(response.status === 409 ? "Sản phẩm đã được sửa ở nơi khác. Hãy tải lại trang trước khi lưu." : String(body?.error ?? "Không thể lưu sản phẩm.")); return; }
    setDocument(normalizeProduct(body)); setSaved("saved");
  }
  async function upload(file: File) {
    setError("");
    const kind = file.type.startsWith("image/") ? "image" : file.type === "video/mp4" ? "video" : file.type === "model/gltf-binary" ? "model" : null;
    if (!kind) { setError("Định dạng upload không được hỗ trợ."); return; }
    const presign = await fetch("/api/uploads/presign", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, contentType: file.type, fileName: file.name, size: file.size }) });
    const intent = await presign.json() as { url?: string; intentId?: string; error?: string };
    if (!presign.ok || !intent.url || !intent.intentId) { setError(intent.error ?? "Không thể tạo upload intent."); return; }
    const put = await fetch(intent.url, { method: "PUT", headers: { "content-type": file.type }, body: file });
    if (!put.ok) { setError("Upload lên kho lưu trữ thất bại."); return; }
    const finalized = await fetch("/api/uploads/finalize", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ intentId: intent.intentId, productId, alt: file.name }) });
    if (!finalized.ok) { setError("Không thể xác nhận media."); return; }
    window.location.reload();
  }
  return <div className="admin-editor"><div className="admin-tabs" role="tablist">{tabs.map((item) => <button key={item} className={item === tab ? "active" : ""} onClick={() => setTab(item)} role="tab" aria-selected={item === tab}>{item}</button>)}</div><div className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">{tab.toUpperCase()}</p><h2>{tab === "Construction" ? "Mattress Lab" : `Product ${tab}`}</h2></div><span className="admin-saved">{saved === "saved" ? "Saved just now" : saved === "saving" ? "Saving…" : saved === "error" ? "Save failed" : "Draft changes"}</span></div>
    {tab === "General" && <div className="admin-form"><label>Product name<input value={document.general.name} onChange={(event) => updateGeneral("name", event.target.value)} /></label><label>Eyebrow<input value={document.general.eyebrow ?? ""} onChange={(event) => updateGeneral("eyebrow", event.target.value || null)} /></label><label className="full">Description<textarea value={document.general.description ?? ""} onChange={(event) => updateGeneral("description", event.target.value || null)} rows={5} /></label><label>Status<select value={document.general.status} onChange={(event) => updateGeneral("status", event.target.value as "DRAFT" | "PUBLISHED")}><option value="PUBLISHED">PUBLISHED</option><option value="DRAFT">DRAFT</option></select></label><label>Demo product<input type="checkbox" checked={document.general.isDemo} onChange={(event) => updateGeneral("isDemo", event.target.checked)} /></label><label>Mattress Lab<input type="checkbox" checked={document.general.mattressLab} onChange={(event) => updateGeneral("mattressLab", event.target.checked)} /></label><label className="full">Poster URL<input value={document.general.posterUrl ?? ""} onChange={(event) => updateGeneral("posterUrl", event.target.value || null)} /></label><label className="full">Model URL<input value={document.general.modelUrl ?? ""} onChange={(event) => updateGeneral("modelUrl", event.target.value || null)} /></label></div>}
    {tab === "Pricing" && <div className="admin-note">Giá được lưu trên từng variant. Khi price trống hoặc sản phẩm là demo, storefront hiển thị Liên hệ và khóa checkout.</div>}
    {tab === "Variants" && <div className="admin-table"><div className="admin-row admin-row-head"><span>Variant</span><span>Price</span><span>Stock (read-only)</span><span>Active</span></div>{document.variants.map((variant, index) => <div className="admin-row" key={variant.id ?? `new-${index}`}><span><input aria-label="Width" type="number" value={variant.width} onChange={(event) => updateVariant(index, { width: Number(event.target.value) })} /> × <input aria-label="Length" type="number" value={variant.length} onChange={(event) => updateVariant(index, { length: Number(event.target.value) })} /> × <input aria-label="Thickness" type="number" value={variant.thickness} onChange={(event) => updateVariant(index, { thickness: Number(event.target.value) })} /> <input aria-label="SKU" placeholder="SKU bắt buộc" value={variant.sku} onChange={(event) => updateVariant(index, { sku: event.target.value })} /></span><input aria-label="Price" type="number" min="0" value={variant.price ?? ""} onChange={(event) => updateVariant(index, { price: event.target.value ? Number(event.target.value) : null })} /><output aria-label="Stock">{variant.stock}</output><input aria-label="Active" type="checkbox" checked={variant.active} onChange={(event) => updateVariant(index, { active: event.target.checked })} /></div>)}<button className="button button-secondary" onClick={() => setDocument((current) => ({ ...current, variants: [...current.variants, { width: 160, length: 200, thickness: 15, price: null, compareAtPrice: null, sku: "", stock: 0, active: false }] }))}>Add variant</button></div>}
    {tab === "Media" && <div className="admin-media-grid"><label className="upload-card">+<span>Upload image / video / GLB</span><small>R2 presigned upload</small><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,model/gltf-binary,.glb" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label>{document.media.map((file) => <div className="media-card" key={file.id ?? file.url}><img src={file.url} alt={file.alt} /><span>{file.url.split("/").pop()}</span><small>{file.isDemo ? "Demo asset" : "CMS asset"} · focal point {Math.round(file.focalX * 100)} / {Math.round(file.focalY * 100)}</small></div>)}</div>}
    {tab === "Construction" && <div className="construction-editor"><div className="lab-switch"><span>Mattress Lab</span><input type="checkbox" checked={document.general.mattressLab} onChange={(event) => updateGeneral("mattressLab", event.target.checked)} /></div><label className="upload-card wide">Upload GLB model <small>Lazy loaded on storefront · max 50MB</small><input type="file" accept="model/gltf-binary,.glb" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label>{document.layers.map((layer, index) => <div className="layer-row" key={layer.id ?? `layer-${index}`}><b>{String(layer.sortOrder + 1).padStart(2, "0")}</b><input value={layer.name} onChange={(event) => updateLayer(index, { name: event.target.value })} /><input placeholder="Material" value={layer.material ?? ""} onChange={(event) => updateLayer(index, { material: event.target.value || null })} /><input placeholder="GLB node" value={layer.nodeName ?? ""} onChange={(event) => updateLayer(index, { nodeName: event.target.value || null })} /><input type="checkbox" checked={layer.published} onChange={(event) => updateLayer(index, { published: event.target.checked })} /></div>)}</div>}
    {tab === "Inventory" && <div className="admin-note">Tồn kho được quản lý theo variant. Mọi thay đổi mua hàng vẫn được kiểm tra lại trong transaction server.</div>}{tab === "Shipping" && <div className="admin-note">Phí vận chuyển và thông tin chuyển khoản được quản lý tại Site settings.</div>}{tab === "SEO" && <div className="admin-note">SEO metadata chỉ được xuất bản khi nội dung đã được xác nhận trong CMS.</div>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary admin-save" disabled={saved === "saving"} onClick={() => void save()}>{saved === "saving" ? "Saving…" : "Save changes"}</button></div></div>;
}
