"use client";

import { useState } from "react";

type Item = { id: string; orderId: string; orderCode: string; productName: string; sku: string };
export function AfterSalesForm({ items }: { items: Item[] }) {
  const [itemId, setItemId] = useState(items[0]?.id ?? ""); const [type, setType] = useState("WARRANTY_REVIEW"); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); const item = items.find((entry) => entry.id === itemId); if (!item) return; setSaving(true); setMessage(""); const response = await fetch("/api/account/after-sales", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: item.orderId, orderItemId: item.id, type, subject, description }) }); const body = await response.json().catch(() => null) as { error?: string } | null; setSaving(false); if (!response.ok) { setMessage(body?.error ?? "Không thể gửi yêu cầu."); return; } setMessage("Yêu cầu đã được tiếp nhận để kiểm tra."); setSubject(""); setDescription(""); }
  return <form className="account-form" onSubmit={submit} aria-label="Yêu cầu kiểm tra bảo hành hoặc hỗ trợ"><label>Sản phẩm trong đơn hàng<select required value={itemId} onChange={(event) => setItemId(event.target.value)}>{items.map((item) => <option key={item.id} value={item.id}>{item.orderCode} · {item.productName} · {item.sku}</option>)}</select></label><label>Loại yêu cầu<select value={type} onChange={(event) => setType(event.target.value)}><option value="WARRANTY_REVIEW">Yêu cầu kiểm tra bảo hành</option><option value="PRODUCT_SUPPORT">Hỗ trợ sản phẩm</option></select></label><label>Tiêu đề<input required minLength={2} maxLength={160} value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label>Nội dung<textarea required minLength={10} maxLength={4000} rows={8} value={description} onChange={(event) => setDescription(event.target.value)} /></label>{message && <p role="status" aria-live="polite">{message}</p>}<button className="button button-primary" disabled={saving || !itemId}>{saving ? "Đang gửi…" : "Gửi yêu cầu"}</button></form>;
}
