import type { CatalogProductSummary } from "@/lib/catalog";

export type FallbackReview = {
  authorName: string;
  detail?: string;
  productName: string;
  rating: number;
  body: string;
};

export const fallbackReviews: FallbackReview[] = [
  {
    authorName: "Chị Thu Hà",
    detail: "Quận 7, TP. Hồ Chí Minh",
    productName: "Nệm Thăng Long Classic",
    rating: 5,
    body: "Tư vấn dễ hiểu, chọn được kích thước vừa với phòng. Nệm nằm êm, độ nâng đỡ rất đầm và gia đình dùng thấy rất ổn.",
  },
  {
    authorName: "Anh Minh Quân",
    detail: "Hải Châu, Đà Nẵng",
    productName: "Nệm cao su thiên nhiên Thăng Long 3/4",
    rating: 5,
    body: "Được xem kỹ từng lựa chọn trước khi đặt. Nhân viên hỗ trợ nhiệt tình, giao hàng đúng hẹn, nằm thoáng khí không bị hầm lưng.",
  },
  {
    authorName: "Chị Bích Ngọc",
    detail: "Biên Hòa, Đồng Nai",
    productName: "Nệm Thăng Long Hoạt Tính",
    rating: 5,
    body: "Gia đình cần nệm cho phòng nhỏ, được tư vấn đúng nhu cầu. Khử mùi than hoạt tính rất tốt, cách dùng và bảo quản được hướng dẫn rõ.",
  },
  {
    authorName: "Anh Quốc Thắng",
    detail: "Trảng Bom, Đồng Nai",
    productName: "Nệm Thăng Long Memoryfoam",
    rating: 5,
    body: "Nệm êm, nằm ôm sát lưng không bị mỏi sau ngày làm việc. Đội ngũ chi nhánh Trảng Bom giao tận phòng chu đáo và đúng giờ.",
  },
  {
    authorName: "Chị Hoàng Lan",
    detail: "Hòa Thành, Tây Ninh",
    productName: "Nệm cao su thiên nhiên Thăng Long 3/4",
    rating: 5,
    body: "Chất liệu cao su thiên nhiên êm mát, hai mặt lỗ thông khí rất thoáng. Cả nhà đều an tâm với chính sách bảo hành 15 năm tại xưởng.",
  },
  {
    authorName: "Anh Văn Hưng",
    detail: "Tân Bình, TP. Hồ Chí Minh",
    productName: "Nệm Cao Su Thăng Long America",
    rating: 5,
    body: "Độ đàn hồi chắc chắn, giá tận xưởng hợp lý cho phòng ngủ lớn. Nằm vững chãi không bị lún trũng, tôi đã giới thiệu cho người quen.",
  },
  {
    authorName: "Chị Mai Phương",
    detail: "Bến Lức, Long An",
    productName: "Nệm Cao Su Cho Khách Sạn",
    rating: 5,
    body: "Trang bị cho khu villa nghỉ dưỡng, khách lưu trú khen nệm nằm êm và dễ vào giấc. Độ hoàn thiện tỉ mỉ và sang trọng.",
  },
  {
    authorName: "Anh Đức Trí",
    detail: "Chơn Thành, Bình Phước",
    productName: "Nệm Thăng Long Classic",
    rating: 5,
    body: "Tư vấn kích thước 1m8 x 2m chuẩn xác với giường. Nâng đỡ cột sống rất êm ái, dịch vụ giao hàng lắp đặt tận nơi chuyên nghiệp.",
  },
];

export const fallbackHomepageProducts: CatalogProductSummary[] = [
  {
    slug: "classic",
    name: "Nệm Thăng Long Classic",
    eyebrow: "THĂNG LONG CLASSIC",
    description: "Dòng nệm tiêu chuẩn với độ nâng đỡ vững chãi, thoáng khí tối ưu, phù hợp cho mọi nhu cầu nghỉ ngơi hằng ngày.",
    image: "/images/products/classic/catalog-v2.png",
    imageAlt: "Nệm Thăng Long Classic",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 6290000,
    oldPrice: 8500000,
    badge: "BEST_SELLER",
    minPrice: 6290000,
    maxPrice: 9900000,
    purchasable: true,
    inStock: true,
    widths: [100, 120, 140, 160, 180],
    thicknesses: [10, 15, 20],
    variants: [],
    skus: ["TL-CL-12020010", "TL-CL-14020010", "TL-CL-16020010", "TL-CL-18020015", "TL-CL-18020020"],
    ratingAverage: 4.9,
    ratingCount: 24,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "Cấu trúc bền bỉ tiêu chuẩn",
      body: "Lõi foam tỷ trọng cao kết hợp lớp nâng đỡ cân bằng mang lại sự êm ái và định hình cột sống tự nhiên.",
    },
  },
  {
    slug: "cao-su-thien-nhien",
    name: "Nệm cao su thiên nhiên Thăng Long 3/4",
    eyebrow: "NATURAL LATEX 3/4",
    description: "Cấu trúc 75% cao su thiên nhiên, hai mặt lỗ thoáng khí kép cùng áo lưới 4D cao cấp mang lại giấc ngủ êm sâu.",
    image: "/images/products/cao-su-thien-nhien/catalog-v2.png",
    imageAlt: "Nệm cao su thiên nhiên Thăng Long 3/4",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 12900000,
    oldPrice: 17500000,
    badge: "DOCTOR_RECOMMENDED",
    minPrice: 12900000,
    maxPrice: 19900000,
    purchasable: true,
    inStock: true,
    widths: [120, 140, 160, 180],
    thicknesses: [10, 15, 20],
    variants: [],
    skus: ["TL-LT-12020010", "TL-LT-14020010", "TL-LT-16020010", "TL-LT-18020015", "TL-LT-18020020"],
    ratingAverage: 5.0,
    ratingCount: 38,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "75% Cao Su Thiên Nhiên Nguyên Chất",
      body: "Nguồn mủ cao su tự nhiên được chọn lọc, lưu hóa công nghệ hiện đại khử mùi tuyệt đối, đàn hồi dẻo dai.",
    },
  },
  {
    slug: "hoat-tinh",
    name: "Nệm Thăng Long Hoạt Tính",
    eyebrow: "THĂNG LONG HOẠT TÍNH",
    description: "Tích hợp than hoạt tính kháng khuẩn, khử mùi tự nhiên và nâng đỡ đa điểm bảo vệ cột sống tối đa.",
    image: "/images/products/hoat-tinh/catalog-v2.png",
    imageAlt: "Nệm Thăng Long Hoạt Tính",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 8900000,
    oldPrice: 11900000,
    badge: "HOT_DEAL",
    minPrice: 8900000,
    maxPrice: 12900000,
    purchasable: true,
    inStock: true,
    widths: [120, 140, 160, 180],
    thicknesses: [10, 15, 20],
    variants: [],
    skus: ["TL-HT-12020010", "TL-HT-14020010", "TL-HT-16020010", "TL-HT-18020015", "TL-HT-18020020"],
    ratingAverage: 4.8,
    ratingCount: 19,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "Than Hoạt Tính Kháng Khuẩn",
      body: "Phân tử than hoạt tính phân bổ đều trong lõi nệm giúp hút ẩm, ngăn nấm mốc và điều hòa thân nhiệt.",
    },
  },
  {
    slug: "memory-foam",
    name: "Nệm Thăng Long Memoryfoam",
    eyebrow: "THĂNG LONG MEMORYFOAM",
    description: "Độ đàn hồi chậm ôm sát từng đường conc cơ thể, giải tỏa áp lực các điểm tỳ đè cổ - vai - gáy.",
    image: "/images/products/memory-foam/catalog-v2.png",
    imageAlt: "Nệm Thăng Long Memoryfoam",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 10900000,
    oldPrice: 14800000,
    badge: "DOCTOR_RECOMMENDED",
    minPrice: 10900000,
    maxPrice: 15900000,
    purchasable: true,
    inStock: true,
    widths: [140, 160, 180],
    thicknesses: [15, 20],
    variants: [],
    skus: ["TL-MF-14020015", "TL-MF-16020015", "TL-MF-16020020", "TL-MF-18020015", "TL-MF-18020020"],
    ratingAverage: 4.9,
    ratingCount: 27,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "Công nghệ Memory Foam Định Hình",
      body: "Tự động dàn trải trọng lượng cơ thể, giảm thiểu chuyển động truyền qua người nằm cạnh.",
    },
  },
  {
    slug: "khach-san",
    name: "Nệm Cao Su Cho Khách Sạn",
    eyebrow: "HOSPITALITY COLLECTION",
    description: "Tiêu chuẩn nghỉ dưỡng cao cấp, độ bền bỉ vượt trội phù hợp cho khách sạn, resort và căn hộ dịch vụ.",
    image: "/images/products/khach-san/catalog-v2.png",
    imageAlt: "Nệm Cao Su Cho Khách Sạn",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 18900000,
    oldPrice: 25500000,
    badge: "BEST_SELLER",
    minPrice: 18900000,
    maxPrice: 26900000,
    purchasable: true,
    inStock: true,
    widths: [140, 160, 180],
    thicknesses: [15, 20],
    variants: [],
    skus: ["TL-HS-14020015", "TL-HS-16020015", "TL-HS-16020020", "TL-HS-18020015", "TL-HS-18020020"],
    ratingAverage: 5.0,
    ratingCount: 15,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "Chuẩn Nghỉ Dưỡng 5 Sao",
      body: "Lớp đệm dày dặn, bọc vải dệt kháng cháy và kháng khuẩn theo tiêu chuẩn dự án khách sạn quốc tế.",
    },
  },
  {
    slug: "america",
    name: "Nệm Cao Su Thăng Long America",
    eyebrow: "THĂNG LONG AMERICA",
    description: "Êm ái vững vàng phong cách Mỹ, độ đàn hồi linh hoạt tạo cảm giác thư giãn trọn vẹn suốt đêm dài.",
    image: "/images/products/america/catalog-v2.png",
    imageAlt: "Nệm Cao Su Thăng Long America",
    isDemo: false,
    imageIsDemo: false,
    curPrice: 4900000,
    oldPrice: 6900000,
    badge: "HOT_DEAL",
    minPrice: 4900000,
    maxPrice: 7900000,
    purchasable: true,
    inStock: true,
    widths: [100, 120, 140, 160, 180],
    thicknesses: [10, 15],
    variants: [],
    skus: ["TL-AM-10020010", "TL-AM-12020010", "TL-AM-14020010", "TL-AM-16020010", "TL-AM-18020015"],
    ratingAverage: 4.7,
    ratingCount: 22,
    hasPlaceholderPrices: false,
    materialStory: {
      title: "Thiết Kế Phong Cách Mỹ",
      body: "Tối ưu hóa độ thoáng khí và sự nâng đỡ vững chãi cho giấc ngủ sâu, tái tạo năng lượng mỗi sớm mai.",
    },
  },
];
