import type { Product } from "./types";

export const luxuryProduct: Product = {
  id: "demo-luxury",
  slug: "luxury",
  name: "Nệm Thăng Long Luxury",
  eyebrow: "THE THĂNG LONG SIGNATURE",
  description:
    "Một trải nghiệm nghỉ ngơi cân bằng giữa độ êm, độ nâng đỡ và sự hồi đáp tự nhiên. Được phát triển để bạn cảm thấy thoải mái ngay từ khoảnh khắc đầu tiên.",
  mattressLab: true,
  modelUrl: null,
  posterUrl: "/images/luxury-hero.png",
  media: [
    {
      id: "hero",
      type: "image",
      url: "/images/luxury-hero.png",
      alt: "Nệm Thăng Long Luxury trong không gian phòng ngủ ấm áp",
      aspect: "4:5",
      focalX: 0.5,
      focalY: 0.58,
      fit: "cover",
      isDemo: true,
    },
    {
      id: "detail",
      type: "image",
      url: "/images/luxury-detail.png",
      alt: "Chi tiết bề mặt vải và đường may của nệm",
      aspect: "1:1",
      focalX: 0.5,
      focalY: 0.5,
      fit: "cover",
      isDemo: true,
    },
    {
      id: "lifestyle",
      type: "image",
      url: "/images/luxury-lifestyle.png",
      alt: "Không gian phòng ngủ hiện đại với Nệm Thăng Long Luxury",
      aspect: "3:2",
      focalX: 0.5,
      focalY: 0.52,
      fit: "cover",
      isDemo: true,
    },
  ],
  variants: [
    {
      id: "luxury-160-200-15",
      width: 160,
      length: 200,
      thickness: 15,
      price: 18900000,
      compareAtPrice: null,
      sku: "TL-LUX-160-200-15",
      stock: 6,
      active: true,
    },
    {
      id: "luxury-180-200-20",
      width: 180,
      length: 200,
      thickness: 20,
      price: null,
      compareAtPrice: null,
      sku: "TL-LUX-180-200-20",
      stock: 0,
      active: true,
    },
  ],
  layers: [
    { id: "layer-cover", sortOrder: 1, name: "Outer Cover", material: "To be confirmed", published: false },
    { id: "layer-comfort", sortOrder: 2, name: "Comfort Layer", material: "To be confirmed", published: false },
    { id: "layer-responsive", sortOrder: 3, name: "Responsive Layer", material: "To be confirmed", published: false },
    { id: "layer-latex", sortOrder: 4, name: "Natural Latex Layer", material: "To be confirmed", published: false },
    { id: "layer-support", sortOrder: 5, name: "Support Core", material: "To be confirmed", published: false },
  ],
  reviews: [],
};
