import Link from "next/link";
import { auth } from "@/auth";
import { getPrisma } from "@/lib/db";
import { isAdmin } from "@/lib/admin-auth";
import { getAdminDashboard, parseDashboardRange } from "@/lib/admin-dashboard";
import { formatVnd } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function AdminDashboardPage({ searchParams }: { searchParams: Promise<{ range?: string }> }) {
  const session = await auth();
  if (!session) return <main className="admin-placeholder"><h1>Đăng nhập để tiếp tục.</h1><Link href="/dang-nhap">Đăng nhập</Link></main>;
  if (!isAdmin(session)) return <main className="admin-placeholder"><h1>Không có quyền truy cập.</h1><p>Dashboard chỉ dành cho tài khoản ADMIN.</p><Link href="/admin">Quay lại admin</Link></main>;
  const prisma = getPrisma(); if (!prisma) return <main className="admin-placeholder"><h1>Database chưa sẵn sàng.</h1></main>;
  const range = parseDashboardRange((await searchParams).range); const data = await getAdminDashboard(prisma, range).catch(() => null); if (!data) return <main className="admin-placeholder"><h1>Không thể tải dashboard.</h1></main>;
  const statusLabel: Record<string, string> = { PENDING: "Chờ xử lý", CONFIRMED: "Đã xác nhận", PROCESSING: "Đang xử lý", SHIPPED: "Đã giao", COMPLETED: "Hoàn tất", CANCELLED: "Đã hủy" };
  return <main className="admin-placeholder admin-dashboard-page"><div className="admin-leads-heading"><div><Link href="/admin">← Product editor</Link><p className="eyebrow">COMMERCE OS / DASHBOARD</p><h1>Vận hành</h1><p>Dữ liệu trong {range === "30d" ? "30 ngày" : "7 ngày"} gần đây.</p></div><nav><Link className="text-link" href={"/admin/dashboard?range=7d" as never}>7 ngày</Link> <Link className="text-link" href={"/admin/dashboard?range=30d" as never}>30 ngày</Link> <Link className="text-link" href="/admin/settings">Site settings</Link></nav></div><div className="dashboard-metrics"><article><span>Đơn hàng</span><strong>{data.orders.total}</strong></article><article><span>Đã thanh toán</span><strong>{formatVnd(data.payments.paidRevenue)}</strong></article><article><span>Thanh toán chờ</span><strong>{data.payments.pending}</strong></article><article className={data.payments.reviewRequired ? "dashboard-alert" : ""}><span>Payment cần review</span><strong>{data.payments.reviewRequired}</strong><Link href="/admin/orders">Xem Orders</Link></article><article><span>Lead mới / đang xử lý</span><strong>{data.leads.NEW} / {data.leads.IN_PROGRESS}</strong><Link href="/admin/leads">Mở Lead Inbox</Link></article><article><span>After-sales</span><strong>{data.afterSales.SUBMITTED} / {data.afterSales.REVIEWING}</strong><Link href={"/admin/after-sales" as never}>Mở inbox</Link></article><article><span>Variant hết hàng</span><strong>{data.inventory.zeroStockActiveVariants}</strong></article></div><section className="dashboard-section"><h2>Trạng thái đơn hàng</h2><ul>{Object.entries(data.orders.byStatus).map(([status, count]) => <li key={status}><span>{statusLabel[status] ?? status}</span><strong>{count}</strong></li>)}</ul></section><section className="dashboard-section"><h2>Hoạt động gần đây</h2><div className="dashboard-activity"><div><h3>Orders</h3>{data.activity.orders.map((order) => <Link href="/admin/orders" key={order.id}><strong>{order.code}</strong><span>{order.status} · {formatVnd(order.total)}</span></Link>)}</div><div><h3>Leads</h3>{data.activity.leads.map((lead) => <Link href="/admin/leads" key={lead.id}><strong>{lead.fullName}</strong><span>{lead.status} · {lead.phone}</span></Link>)}</div><div><h3>After-sales</h3>{data.activity.afterSales.map((item) => <Link href={"/admin/after-sales" as never} key={item.id}><strong>{item.subject}</strong><span>{item.status} · {item.phone}</span></Link>)}</div></div></section></main>;
}
