export const SHOWCASE_PROFILE = {
  id: "showcase-user",
  name: "Nguyễn Minh Anh",
  email: "minhanh@example.test",
  phone: "0901234567",
  createdAt: new Date("2026-01-15T08:00:00Z"),
};

export const SHOWCASE_ADDRESSES = [
  {
    id: "addr-showcase-1",
    label: "Nhà riêng",
    fullName: "Nguyễn Minh Anh",
    phone: "0901 234 567",
    line1: "123 Đường Minh Họa",
    district: "Quận 1",
    province: "TP. Hồ Chí Minh",
    postalCode: "700000",
  },
  {
    id: "addr-showcase-2",
    label: "Văn phòng",
    fullName: "Nguyễn Minh Anh",
    phone: "0901 234 567",
    line1: "456 Tòa nhà Showcase, Phường 2",
    district: "Quận 3",
    province: "TP. Hồ Chí Minh",
    postalCode: "700000",
  },
];

export const SHOWCASE_ORDERS = [
  {
    id: "ord-showcase-1",
    code: "TL-2026-8942",
    createdAt: new Date("2026-08-18T10:30:00Z"),
    status: "Đang xử lý",
    paymentStatus: "PAID",
    subtotal: 22900000,
    shippingFee: 0,
    total: 22900000,
    paymentMethod: "COD",
    shippingAddress: {
      fullName: "Nguyễn Minh Anh",
      phone: "0901 234 567",
      line1: "123 Đường Minh Họa, Phường Demo",
      district: "Quận 1",
      province: "TP. Hồ Chí Minh",
    },
    items: [
      {
        id: "item-1",
        productName: "Nệm Thăng Long Luxury",
        sku: "TL-LX-16020020",
        width: 160,
        length: 200,
        thickness: 20,
        quantity: 1,
        unitPrice: 22900000,
      },
    ],
    payments: [{ status: "COMPLETED", expiresAt: null, provider: "COD" }],
  },
  {
    id: "ord-showcase-2",
    code: "TL-2026-7811",
    createdAt: new Date("2026-08-10T14:15:00Z"),
    status: "Đang giao",
    paymentStatus: "PAID",
    subtotal: 12100000,
    shippingFee: 0,
    total: 12100000,
    paymentMethod: "BANK_TRANSFER",
    shippingAddress: {
      fullName: "Nguyễn Minh Anh",
      phone: "0901 234 567",
      line1: "123 Đường Minh Họa, Phường Demo",
      district: "Quận 1",
      province: "TP. Hồ Chí Minh",
    },
    items: [
      {
        id: "item-2",
        productName: "Nệm Thăng Long Memory Foam",
        sku: "TL-MF-16020015",
        width: 160,
        length: 200,
        thickness: 15,
        quantity: 1,
        unitPrice: 12100000,
      },
    ],
    payments: [{ status: "COMPLETED", expiresAt: null, provider: "BANK_TRANSFER" }],
  },
  {
    id: "ord-showcase-3",
    code: "TL-2026-6204",
    createdAt: new Date("2026-07-22T09:00:00Z"),
    status: "Hoàn tất",
    paymentStatus: "PAID",
    subtotal: 6900000,
    shippingFee: 0,
    total: 6900000,
    paymentMethod: "MOMO",
    shippingAddress: {
      fullName: "Nguyễn Minh Anh",
      phone: "0901 234 567",
      line1: "456 Tòa nhà Showcase, Phường 2",
      district: "Quận 3",
      province: "TP. Hồ Chí Minh",
    },
    items: [
      {
        id: "item-3",
        productName: "Nệm Thăng Long Classic",
        sku: "TL-CL-12020010",
        width: 120,
        length: 200,
        thickness: 10,
        quantity: 1,
        unitPrice: 6900000,
      },
    ],
    payments: [{ status: "COMPLETED", expiresAt: null, provider: "MOMO" }],
  },
  {
    id: "ord-showcase-4",
    code: "TL-2026-4190",
    createdAt: new Date("2026-06-05T16:45:00Z"),
    status: "Cần hỗ trợ",
    paymentStatus: "PAID",
    subtotal: 15700000,
    shippingFee: 0,
    total: 15700000,
    paymentMethod: "COD",
    shippingAddress: {
      fullName: "Nguyễn Minh Anh",
      phone: "0901 234 567",
      line1: "123 Đường Minh Họa, Phường Demo",
      district: "Quận 1",
      province: "TP. Hồ Chí Minh",
    },
    items: [
      {
        id: "item-4",
        productName: "Nệm Cao Su Thiên Nhiên",
        sku: "TL-LT-16020010",
        width: 160,
        length: 200,
        thickness: 10,
        quantity: 1,
        unitPrice: 15700000,
      },
    ],
    payments: [{ status: "COMPLETED", expiresAt: null, provider: "COD" }],
  },
];

export const SHOWCASE_AFTER_SALES_CASES = [
  {
    id: "case-showcase-1",
    caseNumber: "AS-2026-0042",
    createdAt: new Date("2026-08-19T11:20:00Z"),
    status: "IN_REVIEW",
    type: "WARRANTY_CHECK",
    productName: "Nệm Cao Su Thiên Nhiên",
    orderCode: "TL-2026-4190",
    description: "Yêu cầu kiểm tra kỹ thuật độ êm ái và định kỳ bảo dưỡng sản phẩm.",
  },
];
