import type { Product } from "@/lib/types";

export const SHOWCASE_PRODUCTS: Product[] = [
  {
    id: "showcase-america",
    slug: "america",
    name: "Nệm Thăng Long America",
    eyebrow: "EVERYDAY COMFORT",
    description: "Dòng nệm cơ bản được thiết kế cho sự nâng đỡ vững chãi và cảm giác nằm thoải mái hàng ngày.",
    media: [
      { id: "m-am-1", type: "image", url: "/images/home-america.webp", alt: "Hình ảnh nệm Thăng Long America — Góc chụp tổng thể", isDemo: true },
      { id: "m-am-2", type: "image", url: "/images/homepage-hero.webp", alt: "Hình ảnh nệm Thăng Long America trong không gian phòng ngủ", isDemo: true },
      { id: "m-am-3", type: "image", url: "/images/home-classic.webp", alt: "Chi tiết bề mặt và đường may nệm America", isDemo: true },
    ],
    variants: [
      { id: "var-am-100-200-10", width: 100, length: 200, thickness: 10, price: 4900000, compareAtPrice: 5500000, sku: "TL-AM-10020010", stock: 12, active: true },
      { id: "var-am-120-200-10", width: 120, length: 200, thickness: 10, price: 5500000, compareAtPrice: 6200000, sku: "TL-AM-12020010", stock: 15, active: true },
      { id: "var-am-140-200-10", width: 140, length: 200, thickness: 10, price: 6100000, compareAtPrice: 6800000, sku: "TL-AM-14020010", stock: 10, active: true },
      { id: "var-am-160-200-10", width: 160, length: 200, thickness: 10, price: 6700000, compareAtPrice: 7500000, sku: "TL-AM-16020010", stock: 8, active: true },
      { id: "var-am-160-200-15", width: 160, length: 200, thickness: 15, price: 7300000, compareAtPrice: 8100000, sku: "TL-AM-16020015", stock: 6, active: true },
      { id: "var-am-180-200-15", width: 180, length: 200, thickness: 15, price: 7900000, compareAtPrice: 8800000, sku: "TL-AM-18020015", stock: 5, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
      { rating: 5, comfort: 4, quality: 5, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 6, support: 7, breathability: 8, motionIsolation: 7 },
      audience: { published: true, title: "Phù hợp cho", body: "Gia đình trẻ, người tìm kiếm chiếc nệm bền bỉ, dễ chăm sóc với độ nâng đỡ vừa phải cho mọi tư thế ngủ." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Lõi foam tỷ trọng cao kết hợp lớp đệm thoáng khí và vỏ bọc dệt kim mềm mại, kháng khuẩn." },
      delivery: { published: true, title: "Giao hàng", body: "Hỗ trợ giao hàng theo khu vực và quy chuẩn đóng gói chuẩn hóa của Thăng Long." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Chính sách kiểm tra và hỗ trợ kỹ thuật tận tâm sau mua hàng." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
  {
    id: "showcase-classic",
    slug: "classic",
    name: "Nệm Thăng Long Classic",
    eyebrow: "THE EVERYDAY STANDARD",
    description: "Cấu trúc truyền thống tinh chỉnh cho độ phẳng tiêu chuẩn và cảm giác quen thuộc của gia đình Việt.",
    media: [
      { id: "m-cl-1", type: "image", url: "/images/home-classic.webp", alt: "Hình ảnh nệm Thăng Long Classic — Góc chụp chính diện", isDemo: true },
      { id: "m-cl-2", type: "image", url: "/images/home-america.webp", alt: "Cận cảnh cấu trúc vững chãi nệm Classic", isDemo: true },
      { id: "m-cl-3", type: "image", url: "/images/hotel-project.webp", alt: "Nệm Classic phối hợp cùng nội thất phòng ngủ", isDemo: true },
    ],
    variants: [
      { id: "var-cl-120-200-10", width: 120, length: 200, thickness: 10, price: 6900000, compareAtPrice: 7700000, sku: "TL-CL-12020010", stock: 10, active: true },
      { id: "var-cl-140-200-10", width: 140, length: 200, thickness: 10, price: 7500000, compareAtPrice: 8400000, sku: "TL-CL-14020010", stock: 12, active: true },
      { id: "var-cl-160-200-10", width: 160, length: 200, thickness: 10, price: 8100000, compareAtPrice: 9000000, sku: "TL-CL-16020010", stock: 15, active: true },
      { id: "var-cl-160-200-15", width: 160, length: 200, thickness: 15, price: 8700000, compareAtPrice: 9700000, sku: "TL-CL-16020015", stock: 8, active: true },
      { id: "var-cl-180-200-15", width: 180, length: 200, thickness: 15, price: 9300000, compareAtPrice: 10400000, sku: "TL-CL-18020015", stock: 6, active: true },
      { id: "var-cl-180-200-20", width: 180, length: 200, thickness: 20, price: 9900000, compareAtPrice: 11000000, sku: "TL-CL-18020020", stock: 4, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Vững hơn", firmnessScore: 8, support: 8, breathability: 7, motionIsolation: 7 },
      audience: { published: true, title: "Phù hợp cho", body: "Người thích bề mặt nằm phẳng, nâng đỡ lưng chắc chắn, phù hợp với người lớn tuổi và người quen nằm nệm cứng." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Lõi foam nén mật độ cao duy trì độ phẳng tối đa, không võng lún sau thời gian dài sử dụng." },
      delivery: { published: true, title: "Giao hàng", body: "Giao nhận nguyên tấm hoặc cuộn gọn theo điều kiện không gian nhà ở." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Chính sách kiểm tra định kỳ và hỗ trợ sản phẩm tiêu chuẩn Thăng Long." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
  {
    id: "showcase-hoat-tinh",
    slug: "hoat-tinh",
    name: "Nệm Thăng Long Hoạt Tính",
    eyebrow: "RESPONSIVE COMFORT",
    description: "Kết hợp than hoạt tính hỗ trợ khử mùi và duy trì môi trường ngủ khô thoáng, thanh sạch.",
    media: [
      { id: "m-ht-1", type: "image", url: "/images/home-charcoal.webp", alt: "Hình ảnh nệm Thăng Long Hoạt Tính — Bề mặt than hoạt tính", isDemo: true },
      { id: "m-ht-2", type: "image", url: "/images/home-america.webp", alt: "Góc nghiêng nệm Hoạt Tính", isDemo: true },
      { id: "m-ht-3", type: "image", url: "/images/homepage-hero.webp", alt: "Không gian phòng ngủ cùng nệm Hoạt Tính", isDemo: true },
    ],
    variants: [
      { id: "var-ht-120-200-10", width: 120, length: 200, thickness: 10, price: 8900000, compareAtPrice: 9900000, sku: "TL-HT-12020010", stock: 8, active: true },
      { id: "var-ht-140-200-10", width: 140, length: 200, thickness: 10, price: 9700000, compareAtPrice: 10800000, sku: "TL-HT-14020010", stock: 10, active: true },
      { id: "var-ht-160-200-10", width: 160, length: 200, thickness: 10, price: 10500000, compareAtPrice: 11700000, sku: "TL-HT-16020010", stock: 12, active: true },
      { id: "var-ht-160-200-15", width: 160, length: 200, thickness: 15, price: 11300000, compareAtPrice: 12600000, sku: "TL-HT-16020015", stock: 8, active: true },
      { id: "var-ht-180-200-15", width: 180, length: 200, thickness: 15, price: 12100000, compareAtPrice: 13500000, sku: "TL-HT-18020015", stock: 5, active: true },
      { id: "var-ht-180-200-20", width: 180, length: 200, thickness: 20, price: 12900000, compareAtPrice: 14400000, sku: "TL-HT-18020020", stock: 3, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 6, support: 8, breathability: 9, motionIsolation: 8 },
      audience: { published: true, title: "Phù hợp cho", body: "Người có cơ địa nhạy cảm, dễ đổ mồ hôi đêm hoặc mong muốn không gian phòng ngủ luôn thông thoáng." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Lớp bọt than hoạt tính hữu cơ phân tán vi mô giúp hấp thụ ẩm, kháng khuẩn và duy trì độ trong lành." },
      delivery: { published: true, title: "Giao hàng", body: "Bảo quản màng bọc chống ẩm chuyên dụng trong suốt quá trình vận chuyển." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Hỗ trợ kiểm định chất lượng và tư vấn vệ sinh bảo dưỡng định kỳ." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
  {
    id: "showcase-memory-foam",
    slug: "memory-foam",
    name: "Nệm Thăng Long Memory Foam",
    eyebrow: "CONTOURING COMFORT",
    description: "Khả năng ôm sát đường cong cơ thể, giải tỏa áp lực các điểm tỳ đè và hạn chế truyền rung động.",
    media: [
      { id: "m-mf-1", type: "image", url: "/images/home-memory-foam.webp", alt: "Hình ảnh nệm Memory Foam — Khả năng ôm sát cơ thể", isDemo: true },
      { id: "m-mf-2", type: "image", url: "/images/home-america.webp", alt: "Cận cảnh chất liệu memory foam êm ái", isDemo: true },
      { id: "m-mf-3", type: "image", url: "/images/home-luxury.webp", alt: "Nệm Memory Foam trong phòng ngủ hiện đại", isDemo: true },
    ],
    variants: [
      { id: "var-mf-140-200-15", width: 140, length: 200, thickness: 15, price: 10900000, compareAtPrice: 12200000, sku: "TL-MF-14020015", stock: 8, active: true },
      { id: "var-mf-160-200-15", width: 160, length: 200, thickness: 15, price: 12100000, compareAtPrice: 13500000, sku: "TL-MF-16020015", stock: 10, active: true },
      { id: "var-mf-160-200-20", width: 160, length: 200, thickness: 20, price: 13300000, compareAtPrice: 14800000, sku: "TL-MF-16020020", stock: 6, active: true },
      { id: "var-mf-180-200-15", width: 180, length: 200, thickness: 15, price: 14500000, compareAtPrice: 16200000, sku: "TL-MF-18020015", stock: 5, active: true },
      { id: "var-mf-180-200-20", width: 180, length: 200, thickness: 20, price: 15900000, compareAtPrice: 17700000, sku: "TL-MF-18020020", stock: 4, active: true },
      { id: "var-mf-200-200-20", width: 200, length: 200, thickness: 20, price: 17500000, compareAtPrice: 19500000, sku: "TL-MF-20020020", stock: 0, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
      { rating: 5, comfort: 5, quality: 4, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Êm ái", firmnessScore: 4, support: 8, breathability: 7, motionIsolation: 10 },
      audience: { published: true, title: "Phù hợp cho", body: "Người ngủ nghiêng, người thường đau mỏi vai gáy hoặc cặp đôi cần hạn chế tối đa ảnh hưởng khi người bên cạnh trở mình." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Viscoelastic foam phản ứng theo thân nhiệt và trọng lực, giải tỏa áp lực cột sống hoàn hảo." },
      delivery: { published: true, title: "Giao hàng", body: "Đóng gói chân không bảo vệ foam nguyên vẹn khi chuyển đến nhà." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Cam kết hỗ trợ kiểm tra kỹ thuật và chính sách chăm sóc dài hạn." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
  {
    id: "showcase-cao-su-thien-nhien",
    slug: "cao-su-thien-nhien",
    name: "Nệm Cao Su Thiên Nhiên",
    eyebrow: "NATURAL LATEX DENSITY",
    description: "Chất liệu cao su thiên nhiên chọn lọc với độ đàn hồi tự nhiên và độ bền vững chãi qua thời gian.",
    media: [
      { id: "m-lt-1", type: "image", url: "/images/home-natural-latex.webp", alt: "Hình ảnh Nệm Cao Su Thiên Nhiên — Bề mặt đục lỗ thoáng khí", isDemo: true },
      { id: "m-lt-2", type: "image", url: "/images/home-classic.webp", alt: "Chi tiết độ đàn hồi cao su thiên nhiên", isDemo: true },
      { id: "m-lt-3", type: "image", url: "/images/hotel-project.webp", alt: "Nệm cao su thiên nhiên trong không gian sang trọng", isDemo: true },
    ],
    variants: [
      { id: "var-lt-120-200-10", width: 120, length: 200, thickness: 10, price: 12900000, compareAtPrice: 14400000, sku: "TL-LT-12020010", stock: 8, active: true },
      { id: "var-lt-140-200-10", width: 140, length: 200, thickness: 10, price: 14300000, compareAtPrice: 15900000, sku: "TL-LT-14020010", stock: 7, active: true },
      { id: "var-lt-160-200-10", width: 160, length: 200, thickness: 10, price: 15700000, compareAtPrice: 17500000, sku: "TL-LT-16020010", stock: 10, active: true },
      { id: "var-lt-160-200-15", width: 160, length: 200, thickness: 15, price: 17100000, compareAtPrice: 19100000, sku: "TL-LT-16020015", stock: 6, active: true },
      { id: "var-lt-180-200-15", width: 180, length: 200, thickness: 15, price: 18500000, compareAtPrice: 20600000, sku: "TL-LT-18020015", stock: 5, active: true },
      { id: "var-lt-180-200-20", width: 180, length: 200, thickness: 20, price: 19900000, compareAtPrice: 22200000, sku: "TL-LT-18020020", stock: 3, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
      { rating: 5, comfort: 5, quality: 5, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 6, support: 9, breathability: 9, motionIsolation: 9 },
      audience: { published: true, title: "Phù hợp cho", body: "Người yêu thích chất liệu tự nhiên thuần khiết, mong muốn độ nảy nâng đỡ dẻo dai và tuổi thọ sản phẩm bền lâu." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "100% mủ cao su thiên nhiên tuyển chọn với hàng triệu lỗ thông hơi đối lưu không khí liên tục." },
      delivery: { published: true, title: "Giao hàng", body: "Vận chuyển cẩn trọng với lớp bảo vệ chuyên biệt chống biến dạng cao su." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Chính sách đồng hành bảo dưỡng và hỗ trợ kỹ thuật uy tín từ Thăng Long." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
  {
    id: "showcase-luxury",
    slug: "luxury",
    name: "Nệm Thăng Long Luxury",
    eyebrow: "THE THĂNG LONG SIGNATURE",
    description: "Đỉnh cao chế tác giấc ngủ kết hợp cấu trúc đa tầng thượng hạng, mang lại trải nghiệm nâng đỡ tuyệt đối.",
    media: [
      { id: "m-lx-1", type: "image", url: "/images/home-luxury.webp", alt: "Hình ảnh Nệm Thăng Long Luxury — Bề mặt dệt thủ công", isDemo: true },
      { id: "m-lx-2", type: "image", url: "/images/homepage-hero.webp", alt: "Nệm Luxury trong không gian phòng ngủ master", isDemo: true },
      { id: "m-lx-3", type: "image", url: "/images/hotel-project.webp", alt: "Cấu trúc đa tầng cao cấp của dòng Luxury", isDemo: true },
    ],
    variants: [
      { id: "var-lx-140-200-15", width: 140, length: 200, thickness: 15, price: 18900000, compareAtPrice: 21000000, sku: "TL-LX-14020015", stock: 5, active: true },
      { id: "var-lx-160-200-15", width: 160, length: 200, thickness: 15, price: 20900000, compareAtPrice: 23300000, sku: "TL-LX-16020015", stock: 8, active: true },
      { id: "var-lx-160-200-20", width: 160, length: 200, thickness: 20, price: 22900000, compareAtPrice: 25500000, sku: "TL-LX-16020020", stock: 6, active: true },
      { id: "var-lx-180-200-15", width: 180, length: 200, thickness: 15, price: 24900000, compareAtPrice: 27700000, sku: "TL-LX-18020015", stock: 5, active: true },
      { id: "var-lx-180-200-20", width: 180, length: 200, thickness: 20, price: 26900000, compareAtPrice: 29900000, sku: "TL-LX-18020020", stock: 4, active: true },
      { id: "var-lx-200-200-20", width: 200, length: 200, thickness: 20, price: 29900000, compareAtPrice: 33300000, sku: "TL-LX-20020020", stock: 2, active: true },
    ],
    layers: [
      { id: "layer-1", sortOrder: 1, name: "Vải bọc Organic Damask", material: "Sợi dệt kim cao cấp", thickness: "2cm", description: "Bề mặt mềm mịn, thoáng khí tự nhiên", published: true },
      { id: "layer-2", sortOrder: 2, name: "Lớp nâng đỡ Latex Hybrid", material: "Cao su thiên nhiên kết hợp foam vi mô", thickness: "5cm", description: "Giải tỏa áp lực tức thì", published: true },
      { id: "layer-3", sortOrder: 3, name: "Khối lõi Ortho-Support", material: "Foam mật độ cao gia cường", thickness: "13cm", description: "Nâng đỡ cột sống vững chãi", published: true },
    ],
    mattressLab: true,
    reviews: [
      { rating: 5, comfort: 5, quality: 5, value: 5 },
      { rating: 5, comfort: 5, quality: 5, value: 5 },
      { rating: 5, comfort: 5, quality: 5, value: 5 },
    ],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 6, support: 10, breathability: 9, motionIsolation: 10 },
      audience: { published: true, title: "Phù hợp cho", body: "Khách hàng tìm kiếm trải nghiệm nghỉ ngơi đẳng cấp chuẩn khách sạn 5 sao ngay tại ngôi nhà của mình." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Kết tinh từ các lớp vật liệu tuyển lựa nghiêm ngặt, kết hợp công nghệ may chần tinh xảo bậc nhất." },
      delivery: { published: true, title: "Giao hàng", body: "Dịch vụ giao nhận chuẩn mực, hỗ trợ đặt nệm tận không gian phòng ngủ." },
      warranty: { published: true, title: "Bảo hành & Hỗ trợ", body: "Đặc quyền chăm sóc và bảo hành cao cấp độc quyền từ Thăng Long." },
    },
    isDemo: false,
    source: "database",
    purchasable: true,
  },
];

export function getShowcaseProductBySlug(slug: string): Product | null {
  return SHOWCASE_PRODUCTS.find((product) => product.slug === slug) ?? null;
}
