import type { Product } from "@/lib/types";

export const SHOWCASE_PRODUCTS: Product[] = [
  {
    id: "showcase-america",
    slug: "america",
    name: "Nệm Thăng Long America",
    eyebrow: "EVERYDAY COMFORT",
    description: "Dòng nệm cơ bản phục vụ nhu cầu nghỉ ngơi hàng ngày với cấu trúc bọt foam tiêu chuẩn.",
    media: [
      { id: "m-am-1", type: "image", url: "/images/homepage-range.webp", alt: "Hình ảnh minh họa nệm Thăng Long America — Góc chụp tổng thể", isDemo: true },
      { id: "m-am-2", type: "image", url: "/images/homepage-hero.webp", alt: "Hình ảnh minh họa nệm Thăng Long America trong không gian phòng ngủ", isDemo: true },
      { id: "m-am-3", type: "image", url: "/images/homepage-hotel.webp", alt: "Chi tiết bề mặt và đường may nệm America", isDemo: true },
    ],
    variants: [
      { id: "var-am-100-200-10", width: 100, length: 200, thickness: 10, price: 4900000, compareAtPrice: 5500000, sku: "TL-AM-10020010", stock: 12, active: true },
      { id: "var-am-120-200-10", width: 120, length: 200, thickness: 10, price: 5500000, compareAtPrice: 6200000, sku: "TL-AM-12020010", stock: 15, active: true },
      { id: "var-am-140-200-10", width: 140, length: 200, thickness: 10, price: 6100000, compareAtPrice: 6800000, sku: "TL-AM-14020010", stock: 10, active: true },
      { id: "var-am-160-200-10", width: 160, length: 200, thickness: 10, price: 6700000, compareAtPrice: 7500000, sku: "TL-AM-16020010", stock: 8, active: true },
      { id: "var-am-160-200-15", width: 160, length: 200, thickness: 15, price: 7300000, compareAtPrice: 8100000, sku: "TL-AM-16020015", stock: 6, active: true },
      { id: "var-am-180-200-15", width: 180, length: 200, thickness: 15, price: 7900000, compareAtPrice: 8800000, sku: "TL-AM-18020015", stock: 5, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 3, support: 4, breathability: 4, motionIsolation: 3 },
      audience: { published: true, title: "Phù hợp cho", body: "Nhu cầu trang bị không gian phòng ngủ tiêu chuẩn với cảm giác nằm quen thuộc." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: lõi bọt foam và vải dệt kim." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
  {
    id: "showcase-classic",
    slug: "classic",
    name: "Nệm Thăng Long Classic",
    eyebrow: "THE EVERYDAY STANDARD",
    description: "Cấu trúc truyền thống tinh chỉnh cho độ phẳng tiêu chuẩn và cảm giác quen thuộc của gia đình.",
    media: [
      { id: "m-cl-1", type: "image", url: "/images/homepage-hero.webp", alt: "Hình ảnh minh họa nệm Thăng Long Classic — Góc chụp chính diện", isDemo: true },
      { id: "m-cl-2", type: "image", url: "/images/homepage-range.webp", alt: "Cận cảnh cấu trúc nệm Classic", isDemo: true },
      { id: "m-cl-3", type: "image", url: "/images/homepage-hotel.webp", alt: "Nệm Classic phối hợp cùng nội thất phòng ngủ", isDemo: true },
    ],
    variants: [
      { id: "var-cl-120-200-10", width: 120, length: 200, thickness: 10, price: 6900000, compareAtPrice: 7700000, sku: "TL-CL-12020010", stock: 10, active: true },
      { id: "var-cl-140-200-10", width: 140, length: 200, thickness: 10, price: 7500000, compareAtPrice: 8400000, sku: "TL-CL-14020010", stock: 12, active: true },
      { id: "var-cl-160-200-10", width: 160, length: 200, thickness: 10, price: 8100000, compareAtPrice: 9000000, sku: "TL-CL-16020010", stock: 15, active: true },
      { id: "var-cl-160-200-15", width: 160, length: 200, thickness: 15, price: 8700000, compareAtPrice: 9700000, sku: "TL-CL-16020015", stock: 8, active: true },
      { id: "var-cl-180-200-15", width: 180, length: 200, thickness: 15, price: 9300000, compareAtPrice: 10400000, sku: "TL-CL-18020015", stock: 6, active: true },
      { id: "var-cl-180-200-20", width: 180, length: 200, thickness: 20, price: 9900000, compareAtPrice: 11000000, sku: "TL-CL-18020020", stock: 4, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Vững hơn", firmnessScore: 4, support: 5, breathability: 4, motionIsolation: 3 },
      audience: { published: true, title: "Phù hợp cho", body: "Người quen thuộc với bề mặt nằm phẳng và cảm giác nâng đỡ chắc chắn." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: lõi đệm tỷ trọng cao và lớp bề mặt định hình." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
  {
    id: "showcase-hoat-tinh",
    slug: "hoat-tinh",
    name: "Nệm Thăng Long Hoạt Tính",
    eyebrow: "RESPONSIVE COMFORT",
    description: "Cấu trúc bọt than hoạt tính hỗ trợ cảm giác nằm thanh sạch và môi trường ngủ thoáng mát.",
    media: [
      { id: "m-ht-1", type: "image", url: "/images/homepage-hoat-tinh.webp", alt: "Hình ảnh minh họa nệm Thăng Long Hoạt Tính — Bề mặt than hoạt tính", isDemo: true },
      { id: "m-ht-2", type: "image", url: "/images/homepage-hero.webp", alt: "Góc nghiêng nệm Hoạt Tính", isDemo: true },
      { id: "m-ht-3", type: "image", url: "/images/homepage-hotel.webp", alt: "Không gian phòng ngủ cùng nệm Hoạt Tính", isDemo: true },
    ],
    variants: [
      { id: "var-ht-120-200-10", width: 120, length: 200, thickness: 10, price: 8900000, compareAtPrice: 9900000, sku: "TL-HT-12020010", stock: 8, active: true },
      { id: "var-ht-140-200-10", width: 140, length: 200, thickness: 10, price: 9700000, compareAtPrice: 10800000, sku: "TL-HT-14020010", stock: 10, active: true },
      { id: "var-ht-160-200-10", width: 160, length: 200, thickness: 10, price: 10500000, compareAtPrice: 11700000, sku: "TL-HT-16020010", stock: 12, active: true },
      { id: "var-ht-160-200-15", width: 160, length: 200, thickness: 15, price: 11300000, compareAtPrice: 12600000, sku: "TL-HT-16020015", stock: 8, active: true },
      { id: "var-ht-180-200-15", width: 180, length: 200, thickness: 15, price: 12100000, compareAtPrice: 13500000, sku: "TL-HT-18020015", stock: 5, active: true },
      { id: "var-ht-180-200-20", width: 180, length: 200, thickness: 20, price: 12900000, compareAtPrice: 14400000, sku: "TL-HT-18020020", stock: 3, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 3, support: 4, breathability: 5, motionIsolation: 4 },
      audience: { published: true, title: "Phù hợp cho", body: "Người tìm kiếm cảm giác nằm thông thoáng và môi trường nghỉ ngơi sạch sẽ." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: bọt than hoạt tính và lớp vải thoáng khí." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
  {
    id: "showcase-memory-foam",
    slug: "memory-foam",
    name: "Nệm Thăng Long Memory Foam",
    eyebrow: "CONTOURING COMFORT",
    description: "Cấu trúc memory foam ôm sát đường cong cơ thể và hỗ trợ phân tán áp lực nhẹ nhàng.",
    media: [
      { id: "m-mf-1", type: "image", url: "/images/homepage-memory-foam.webp", alt: "Hình ảnh minh họa nệm Memory Foam — Khả năng ôm sát cơ thể", isDemo: true },
      { id: "m-mf-2", type: "image", url: "/images/homepage-range.webp", alt: "Cận cảnh chất liệu memory foam", isDemo: true },
      { id: "m-mf-3", type: "image", url: "/images/homepage-hero.webp", alt: "Nệm Memory Foam trong phòng ngủ hiện đại", isDemo: true },
    ],
    variants: [
      { id: "var-mf-140-200-15", width: 140, length: 200, thickness: 15, price: 10900000, compareAtPrice: 12200000, sku: "TL-MF-14020015", stock: 8, active: true },
      { id: "var-mf-160-200-15", width: 160, length: 200, thickness: 15, price: 12100000, compareAtPrice: 13500000, sku: "TL-MF-16020015", stock: 10, active: true },
      { id: "var-mf-160-200-20", width: 160, length: 200, thickness: 20, price: 13300000, compareAtPrice: 14800000, sku: "TL-MF-16020020", stock: 6, active: true },
      { id: "var-mf-180-200-15", width: 180, length: 200, thickness: 15, price: 14500000, compareAtPrice: 16200000, sku: "TL-MF-18020015", stock: 5, active: true },
      { id: "var-mf-180-200-20", width: 180, length: 200, thickness: 20, price: 15900000, compareAtPrice: 17700000, sku: "TL-MF-18020020", stock: 4, active: true },
      { id: "var-mf-200-200-20", width: 200, length: 200, thickness: 20, price: 17500000, compareAtPrice: 19500000, sku: "TL-MF-20020020", stock: 0, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Êm ái", firmnessScore: 2, support: 4, breathability: 3, motionIsolation: 5 },
      audience: { published: true, title: "Phù hợp cho", body: "Người tìm kiếm cảm giác êm ái và khả năng giảm ảnh hưởng rung động khi trở mình." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: lớp memory foam đàn hồi chậm kết hợp lõi hỗ trợ." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
  {
    id: "showcase-cao-su-thien-nhien",
    slug: "cao-su-thien-nhien",
    name: "Nệm Cao Su Thiên Nhiên",
    eyebrow: "NATURAL LATEX DENSITY",
    description: "Chất liệu cao su thiên nhiên chọn lọc với độ đàn hồi tự nhiên và cấu trúc thoáng khí đối lưu.",
    media: [
      { id: "m-lt-1", type: "image", url: "/images/homepage-natural-latex.webp", alt: "Hình ảnh minh họa Nệm Cao Su Thiên Nhiên — Bề mặt đục lỗ thoáng khí", isDemo: true },
      { id: "m-lt-2", type: "image", url: "/images/homepage-latex.webp", alt: "Chi tiết độ đàn hồi cao su thiên nhiên", isDemo: true },
      { id: "m-lt-3", type: "image", url: "/images/homepage-hero.webp", alt: "Nệm cao su thiên nhiên trong không gian sang trọng", isDemo: true },
    ],
    variants: [
      { id: "var-lt-120-200-10", width: 120, length: 200, thickness: 10, price: 12900000, compareAtPrice: 14400000, sku: "TL-LT-12020010", stock: 8, active: true },
      { id: "var-lt-140-200-10", width: 140, length: 200, thickness: 10, price: 14300000, compareAtPrice: 15900000, sku: "TL-LT-14020010", stock: 7, active: true },
      { id: "var-lt-160-200-10", width: 160, length: 200, thickness: 10, price: 15700000, compareAtPrice: 17500000, sku: "TL-LT-16020010", stock: 10, active: true },
      { id: "var-lt-160-200-15", width: 160, length: 200, thickness: 15, price: 17100000, compareAtPrice: 19100000, sku: "TL-LT-16020015", stock: 6, active: true },
      { id: "var-lt-180-200-15", width: 180, length: 200, thickness: 15, price: 18500000, compareAtPrice: 20600000, sku: "TL-LT-18020015", stock: 5, active: true },
      { id: "var-lt-180-200-20", width: 180, length: 200, thickness: 20, price: 19900000, compareAtPrice: 22200000, sku: "TL-LT-18020020", stock: 3, active: true },
    ],
    layers: [],
    mattressLab: false,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 3, support: 4, breathability: 5, motionIsolation: 4 },
      audience: { published: true, title: "Phù hợp cho", body: "Người yêu thích chất liệu nguồn gốc thiên nhiên và độ nâng đỡ dẻo dai." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: khối cao su thiên nhiên đúc lỗ đối lưu không khí." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
  {
    id: "showcase-luxury",
    slug: "luxury",
    name: "Nệm Thăng Long Luxury",
    eyebrow: "THE THĂNG LONG SIGNATURE",
    description: "Cấu trúc đa tầng cao cấp kết hợp kỹ thuật chế tác tỉ mỉ cho trải nghiệm nghỉ ngơi trọn vẹn.",
    media: [
      { id: "m-lx-1", type: "image", url: "/images/luxury-hero.webp", alt: "Hình ảnh minh họa Nệm Thăng Long Luxury — Bề mặt dệt thủ công", isDemo: true },
      { id: "m-lx-2", type: "image", url: "/images/luxury-detail.webp", alt: "Nệm Luxury trong không gian phòng ngủ master", isDemo: true },
      { id: "m-lx-3", type: "image", url: "/images/luxury-lifestyle.webp", alt: "Cấu trúc đa tầng cao cấp của dòng Luxury", isDemo: true },
    ],
    variants: [
      { id: "var-lx-140-200-15", width: 140, length: 200, thickness: 15, price: 18900000, compareAtPrice: 21000000, sku: "TL-LX-14020015", stock: 5, active: true },
      { id: "var-lx-160-200-15", width: 160, length: 200, thickness: 15, price: 20900000, compareAtPrice: 23300000, sku: "TL-LX-16020015", stock: 8, active: true },
      { id: "var-lx-160-200-20", width: 160, length: 200, thickness: 20, price: 22900000, compareAtPrice: 25500000, sku: "TL-LX-16020020", stock: 6, active: true },
      { id: "var-lx-180-200-15", width: 180, length: 200, thickness: 15, price: 24900000, compareAtPrice: 27700000, sku: "TL-LX-18020015", stock: 5, active: true },
      { id: "var-lx-180-200-20", width: 180, length: 200, thickness: 20, price: 26900000, compareAtPrice: 29900000, sku: "TL-LX-18020020", stock: 4, active: true },
      { id: "var-lx-200-200-20", width: 200, length: 200, thickness: 20, price: 29900000, compareAtPrice: 33300000, sku: "TL-LX-20020020", stock: 2, active: true },
    ],
    layers: [
      { id: "layer-1", sortOrder: 1, name: "Vải bọc Organic Damask", material: "Sợi dệt kim cao cấp", thickness: "2cm", description: "Bề mặt mềm mại và thông thoáng tự nhiên", published: true },
      { id: "layer-2", sortOrder: 2, name: "Lớp nâng đỡ Latex Hybrid", material: "Cao su thiên nhiên kết hợp bọt foam", thickness: "5cm", description: "Nâng đỡ linh hoạt và êm ái", published: true },
      { id: "layer-3", sortOrder: 3, name: "Khối lõi Ortho-Support", material: "Foam mật độ cao định hình", thickness: "13cm", description: "Nâng đỡ vững chãi cho toàn bộ khối nệm", published: true },
    ],
    mattressLab: true,
    reviews: [],
    content: {
      comfort: { published: true, firmnessLabel: "Cân bằng", firmnessScore: 3, support: 5, breathability: 5, motionIsolation: 5 },
      audience: { published: true, title: "Phù hợp cho", body: "Không gian nghỉ ngơi cao cấp và yêu cầu trải nghiệm giấc ngủ tinh tế." },
      materialStory: { published: true, title: "Cấu trúc vật liệu", body: "Thông tin chất liệu mẫu cho chế độ trình diễn giao diện: cấu trúc đa tầng kết hợp vải dệt cao cấp." },
      delivery: { published: true, title: "Giao hàng", body: "Thông tin quy cách đóng gói và giao nhận mẫu cho chế độ trình diễn giao diện." },
      warranty: { published: true, title: "Hỗ trợ sau mua", body: "Thông tin quy trình hỗ trợ và tiếp nhận sản phẩm mẫu cho chế độ trình diễn giao diện." },
    },
    isDemo: true,
    source: "showcase",
    purchasable: false,
    isShowcase: true,
    previewPurchasable: true,
  },
];

export function getShowcaseProductBySlug(slug: string): Product | null {
  return SHOWCASE_PRODUCTS.find((product) => product.slug === slug) ?? null;
}
